# Generated by Django 5.2.2 on 2025-06-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=60)),
                ('ts', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farm')),
            ],
            options={
                'indexes': [models.Index(fields=['parameter', 'ts'], name='api_sensorr_paramet_9b9df2_idx')],
            },
        ),
    ]
